//! BN254 scalar-field configuration for the outer (BN254-based) proving layer.
//!
//! The field arithmetic and Poseidon2 permutation come from [Plonky3]'s `p3-bn254-fr`
//! crate. The Poseidon2 round constants (width 3) were originally generated by Horizen
//! Labs and are copied verbatim from the `zkhash` reference implementation (authored
//! by Markus Schofnegger and Roman Walch). See [`poseidon2_rc`] for the values and
//! provenance details.
//!
//! [Plonky3]: https://github.com/Plonky3/Plonky3

#![allow(clippy::disallowed_types)]
use std::marker::PhantomData;

pub use p3_bn254_fr::*;
use serde::{Deserialize, Serialize};
use slop_algebra::{ExtensionField, PrimeField31};
use slop_challenger::{IopCtx, MultiField32Challenger};
use slop_poseidon2::{Poseidon2, Poseidon2ExternalMatrixGeneral};
use slop_symmetric::{Hash, MultiField32PaddingFreeSponge, TruncatedPermutation};

mod poseidon2_rc;

use poseidon2_rc::{bn254_from_be_hex, RC3_HEX};

pub const OUTER_CHALLENGER_STATE_WIDTH: usize = 3;
pub const OUTER_DIGEST_SIZE: usize = 1;
pub const OUTER_CHALLENGER_RATE: usize = 2;

#[derive(Debug, Clone, Default, Copy, Serialize, Deserialize, Hash, PartialEq, Eq)]
pub struct Poseidon2Bn254GlobalConfig<F, EF>(PhantomData<(F, EF)>);

pub type OuterPerm = Poseidon2<
    Bn254Fr,
    Poseidon2ExternalMatrixGeneral,
    DiffusionMatrixBN254,
    OUTER_CHALLENGER_STATE_WIDTH,
    5,
>;

pub fn outer_perm() -> OuterPerm {
    const ROUNDS_F: usize = 8;
    const ROUNDS_P: usize = 56;
    let mut round_constants = bn254_poseidon2_rc3();
    let internal_start = ROUNDS_F / 2;
    let internal_end = (ROUNDS_F / 2) + ROUNDS_P;
    let internal_round_constants =
        round_constants.drain(internal_start..internal_end).map(|vec| vec[0]).collect::<Vec<_>>();
    let external_round_constants = round_constants;
    OuterPerm::new(
        ROUNDS_F,
        external_round_constants,
        Poseidon2ExternalMatrixGeneral,
        ROUNDS_P,
        internal_round_constants,
        DiffusionMatrixBN254,
    )
}

pub fn bn254_poseidon2_rc3() -> Vec<[Bn254Fr; 3]> {
    RC3_HEX
        .iter()
        .map(|row| {
            [bn254_from_be_hex(row[0]), bn254_from_be_hex(row[1]), bn254_from_be_hex(row[2])]
        })
        .collect()
}

impl<F: PrimeField31, EF: ExtensionField<F>> IopCtx for Poseidon2Bn254GlobalConfig<F, EF> {
    type F = F;

    type EF = EF;

    type Digest = Hash<F, Bn254Fr, 1>;

    type Challenger = MultiField32Challenger<
        F,
        Bn254Fr,
        OuterPerm,
        OUTER_CHALLENGER_STATE_WIDTH,
        OUTER_CHALLENGER_RATE,
    >;

    type Hasher = MultiField32PaddingFreeSponge<
        F,
        Bn254Fr,
        OuterPerm,
        OUTER_CHALLENGER_STATE_WIDTH,
        16,
        OUTER_DIGEST_SIZE,
    >;

    type Compressor =
        TruncatedPermutation<OuterPerm, 2, OUTER_DIGEST_SIZE, OUTER_CHALLENGER_STATE_WIDTH>;

    fn default_hasher_and_compressor() -> (Self::Hasher, Self::Compressor) {
        let perm = outer_perm();
        let hasher = Self::Hasher::new(perm.clone()).unwrap();
        let compressor = Self::Compressor::new(perm.clone());
        (hasher, compressor)
    }

    fn default_challenger() -> Self::Challenger {
        let default_perm = outer_perm();
        MultiField32Challenger::<
            F,
            Bn254Fr,
            OuterPerm,
            OUTER_CHALLENGER_STATE_WIDTH,
            OUTER_CHALLENGER_RATE,
        >::new(default_perm)
        .unwrap()
    }
}

pub type BNGC<F, EF> = Poseidon2Bn254GlobalConfig<F, EF>;

#[cfg(test)]
mod transcript_regression_tests {
    use super::*;
    use slop_algebra::{
        split_pf_to_field_order_limbs, squeeze_field_order_num_limbs, AbstractField, PrimeField64,
    };
    use slop_challenger::{CanObserve, CanSample};
    use slop_koala_bear::KoalaBear;
    use slop_symmetric::Hash;

    type Challenger = MultiField32Challenger<KoalaBear, Bn254Fr, OuterPerm, 3, 2>;

    #[test]
    fn partial_chunk_padding_changes_the_challenge() {
        let mut short = Challenger::new(outer_perm()).unwrap();
        short.observe(KoalaBear::one());
        let short_challenge: KoalaBear = short.sample();

        let mut padded = Challenger::new(outer_perm()).unwrap();
        padded.observe(KoalaBear::one());
        padded.observe(KoalaBear::zero());
        let padded_challenge: KoalaBear = padded.sample();

        assert_ne!(short_challenge, padded_challenge);
    }

    #[test]
    fn upper_squeeze_bits_change_the_output_limbs() {
        let limb_count = squeeze_field_order_num_limbs::<Bn254Fr, KoalaBear>();
        let low = Bn254Fr::one();
        let high = Bn254Fr::two().exp_u64(64) + low;
        assert_ne!(
            split_pf_to_field_order_limbs::<Bn254Fr, KoalaBear>(low, limb_count),
            split_pf_to_field_order_limbs::<Bn254Fr, KoalaBear>(high, limb_count)
        );
    }

    #[test]
    fn high_digest_bits_change_the_challenge() {
        let mut low = Challenger::new(outer_perm()).unwrap();
        low.observe(Hash::from([Bn254Fr::one()]));
        let low_challenge: KoalaBear = low.sample();

        let mut high = Challenger::new(outer_perm()).unwrap();
        high.observe(Hash::from([Bn254Fr::from_canonical_u64(KoalaBear::ORDER_U64 + 1)]));
        let high_challenge: KoalaBear = high.sample();

        assert_ne!(low_challenge, high_challenge);
    }
}
